<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular, FileImageRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/混乱博物馆/Vol.151-200/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.151 永动机的失败教训.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "49.58 MB",
  },
  {
    key: 1,
    name: "Vol.152 中国的领土从哪来.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "59.09 MB",
  },
  {
    key: 2,
    name: "Vol.153 钢铁是怎样炼成的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "77.57 MB",
  },
  {
    key: 3,
    name: "Vol.154 人类壮阳简史.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.02 MB",
  },
  {
    key: 4,
    name: "Vol.155 星星与绝对真理.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "31.0 MB",
  },
  {
    key: 5,
    name: "Vol.156 巨物是怎样长成的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "61.49 MB",
  },
  {
    key: 6,
    name: "Vol.157 荧光尿中的色彩起源.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.75 MB",
  },
  {
    key: 7,
    name: "Vol.158 迷情巧克力.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "59.21 MB",
  },
  {
    key: 8,
    name: "Vol.159 命运是什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.35 MB",
  },
  {
    key: 9,
    name: "Vol.160 水银为什么是液体.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "21.44 MB",
  },
  {
    key: 10,
    name: "Vol.161 什么是物质.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "67.35 MB",
  },
  {
    key: 11,
    name: "Vol.162 汽车的历史.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "72.95 MB",
  },
  {
    key: 12,
    name: "Vol.163 追溯中国人的面貌起源.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "48.73 MB",
  },
  {
    key: 13,
    name: "Vol.164 如何给动物分类.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "13.59 MB",
  },
  {
    key: 14,
    name: "Vol.165 汞的剧毒.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.02 MB",
  },
  {
    key: 15,
    name: "Vol.166 肌肉的力量.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.69 MB",
  },
  {
    key: 16,
    name: "Vol.167 怎样射得更远.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.74 MB",
  },
  {
    key: 17,
    name: "Vol.168 为什么中年男子容易脱发.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.14 MB",
  },
  {
    key: 18,
    name: "Vol.169 人类避孕简史.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "27.35 MB",
  },
  {
    key: 19,
    name: "Vol.170 阴毒的铅.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "59.35 MB",
  },
  {
    key: 20,
    name: "Vol.171 为什么只有恐龙和人用两条腿走路.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.14 MB",
  },
  {
    key: 21,
    name: "Vol.172 玻璃是如何练成的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "65.53 MB",
  },
  {
    key: 22,
    name: "Vol.173 通过了图灵测试，距离意识有多远？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.85 MB",
  },
  {
    key: 23,
    name: "Vol.174 头发为什么这么长.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "38.66 MB",
  },
  {
    key: 24,
    name: "Vol.175 艺术起源于什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "71.77 MB",
  },
  {
    key: 25,
    name: "Vol.176 星辰怎样繁殖.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "71.05 MB",
  },
  {
    key: 26,
    name: "Vol.177 黑白键的故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "26.7 MB",
  },
  {
    key: 27,
    name: "Vol.178 穿越时空的巴赫.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "62.25 MB",
  },
  {
    key: 28,
    name: "Vol.179 永恒的巴赫.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "68.05 MB",
  },
  {
    key: 29,
    name: "Vol.180 计算机之前的计算机.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.7 MB",
  },
  {
    key: 30,
    name: "Vol.181 全体自然数的和等于-1_12.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "23.42 MB",
  },
  {
    key: 31,
    name: "Vol.182 猫和狗不懂美食.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.38 MB",
  },
  {
    key: 32,
    name: "Vol.183 找准人类的位置.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "95.66 MB",
  },
  {
    key: 33,
    name: "Vol.184 吃凤梨，泡盐水干什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "49.62 MB",
  },
  {
    key: 34,
    name: "Vol.185 男人会消失吗.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "66.7 MB",
  },
  {
    key: 35,
    name: "Vol.186 快把弗洛伊德的书扔掉！.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.49 MB",
  },
  {
    key: 36,
    name: "Vol.187 本期没有节目.jpg",
    type: <FileImageRegular />,
    type_name: "image",
    time: "2021.9.29",
    size: "23.8 KB",
  },
  {
    key: 37,
    name: "Vol.188 大統一理论之梦.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "48.66 MB",
  },
  {
    key: 38,
    name: "Vol.189 这才是心理学.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.88 MB",
  },
  {
    key: 39,
    name: "Vol.190 怎样对对联.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.95 MB",
  },
  {
    key: 40,
    name: "Vol.191 爱上青花·內篇.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "68.04 MB",
  },
  {
    key: 41,
    name: "Vol.192 爱上青花·外篇.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "83.23 MB",
  },
  {
    key: 42,
    name: "Vol.193 天然的毒.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.09 MB",
  },
  {
    key: 43,
    name: "Vol.194 史上最危险的论文.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "63.61 MB",
  },
  {
    key: 44,
    name: "Vol.195 做人怎么长脸.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.57 MB",
  },
  {
    key: 45,
    name: "Vol.196 发光的骨头.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "59.13 MB",
  },
  {
    key: 46,
    name: "Vol.197 钚和镭的毒.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "23.32 MB",
  },
  {
    key: 47,
    name: "Vol.198 星座的起源.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "55.85 MB",
  },
  {
    key: 48,
    name: "Vol.199 黃金分割的妙处.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "46.64 MB",
  },
  {
    key: 49,
    name: "Vol.200 为什么绝大多数海螺都向右旋转.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "29.51 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
