<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/混乱博物馆/Vol.1-50/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.001 鲁本斯为何画这三颗星.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "13.42 MB",
  },
  {
    key: 1,
    name: "Vol.002 光荣的遮羞布.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "25.57 MB",
  },
  {
    key: 2,
    name: "Vol.003 史上最危险的儿童玩具.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "16.54 MB",
  },
  {
    key: 3,
    name: "Vol.004 藏在你脸皮下的鱼.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "10.84 MB",
  },
  {
    key: 4,
    name: "Vol.005 为什么会有倒悬的彩虹？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "12.27 MB",
  },
  {
    key: 5,
    name: "Vol.006 荒诞怪：挑战你对脊椎动物的极限想象.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "18.0 MB",
  },
  {
    key: 6,
    name: "Vol.007 被光干涉的蝴蝶翅膀.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "21.72 MB",
  },
  {
    key: 7,
    name: "Vol.008 莫奈的紫外世界.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.08 MB",
  },
  {
    key: 8,
    name: "Vol.009 雨的味道从哪来？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "18.14 MB",
  },
  {
    key: 9,
    name: "Vol.010 圣诞岛红蟹大迁徙.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "59.75 MB",
  },
  {
    key: 10,
    name: "Vol.011 特立独行的天体轨道.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "12.09 MB",
  },
  {
    key: 11,
    name: "Vol.012 不存在的洛杉矶.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.18 MB",
  },
  {
    key: 12,
    name: "Vol.013 引导埃及先民的天狼星.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.32 MB",
  },
  {
    key: 13,
    name: "Vol.014 唱片发明前的唱片.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "38.3 MB",
  },
  {
    key: 14,
    name: "Vol.015 脐橙的脐是什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "16.69 MB",
  },
  {
    key: 15,
    name: "Vol.016 英文字母从哪来.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "22.17 MB",
  },
  {
    key: 16,
    name: "Vol.017 怎样画黑魔法符咒.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "34.38 MB",
  },
  {
    key: 17,
    name: "Vol.018 撞上反物质会变成什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "30.14 MB",
  },
  {
    key: 18,
    name: "Vol.019 一组混乱的展品.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "61.89 MB",
  },
  {
    key: 19,
    name: "Vol.020 兰花的阴谋.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.11 MB",
  },
  {
    key: 20,
    name: "Vol.021 辉煌的障眼法.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "74.73 MB",
  },
  {
    key: 21,
    name: "Vol.022 琴弦上的数学危机.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "21.16 MB",
  },
  {
    key: 22,
    name: "Vol.023 糟糕的物理常数.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "22.45 MB",
  },
  {
    key: 23,
    name: "Vol.024 海带不是植物.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.49 MB",
  },
  {
    key: 24,
    name: "Vol.025 每个人都是小宇宙.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "64.88 MB",
  },
  {
    key: 25,
    name: "Vol.026 我们找到了两片一样的雪花.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.74 MB",
  },
  {
    key: 26,
    name: "Vol.027 吉他就是琵琶.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.58 MB",
  },
  {
    key: 27,
    name: "Vol.028 达芬奇没有密码.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "46.14 MB",
  },
  {
    key: 28,
    name: "Vol.029 猫和狗的千万年恩怨.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "48.6 MB",
  },
  {
    key: 29,
    name: "Vol.030 金子为什么是金色.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "37.47 MB",
  },
  {
    key: 30,
    name: "Vol.031 怎样补充胶原蛋白.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "30.51 MB",
  },
  {
    key: 31,
    name: "Vol.032 寄生蜂的黑客特工.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.87 MB",
  },
  {
    key: 32,
    name: "Vol.033 欧洲板甲简史.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "73.22 MB",
  },
  {
    key: 33,
    name: "Vol.034 玛雅人的历法.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "34.46 MB",
  },
  {
    key: 34,
    name: "Vol.035 龙的简史.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "79.17 MB",
  },
  {
    key: 35,
    name: "Vol.036 阉割父亲的故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "67.14 MB",
  },
  {
    key: 36,
    name: "Vol.037 生命有戏：另一种计算机.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "55.08 MB",
  },
  {
    key: 37,
    name: "Vol.038 恐龙前第二帝国.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.13 MB",
  },
  {
    key: 38,
    name: "Vol.039 人为什么有五根指头.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "39.73 MB",
  },
  {
    key: 39,
    name: "Vol.040 埃舍尔和镶嵌.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "74.61 MB",
  },
  {
    key: 40,
    name: "Vol.041 什么是卡农.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "27.29 MB",
  },
  {
    key: 41,
    name: "Vol.042 蛙的育儿之道.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.72 MB",
  },
  {
    key: 42,
    name: "Vol.043 狂战士吃了马里奥的红蘑菇.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.64 MB",
  },
  {
    key: 43,
    name: "Vol.044 从星云开始的沉与浮.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "55.87 MB",
  },
  {
    key: 44,
    name: "Vol.045 发条珍宝展.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "63.69 MB",
  },
  {
    key: 45,
    name: "Vol.046 为什么中国人爱玉，印度人爱宝石.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.72 MB",
  },
  {
    key: 46,
    name: "Vol.047 红色的血与绿色的血.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "37.22 MB",
  },
  {
    key: 47,
    name: "Vol.048 大使们的骷髅.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "58.83 MB",
  },
  {
    key: 48,
    name: "Vol.049 一种新的穿越方式.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "61.85 MB",
  },
  {
    key: 49,
    name: "Vol.050 眼睛从哪来.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "29.37 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
