<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/混乱博物馆/Vol.51-100/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.051 彩色的生命和生命的色彩.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.55 MB",
  },
  {
    key: 1,
    name: "Vol.052 瓦雷利亚语的真实与虚幻.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "100.6 MB",
  },
  {
    key: 2,
    name: "Vol.053 无夏之年.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "48.34 MB",
  },
  {
    key: 3,
    name: "Vol.054 光年不止是长度.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.3 MB",
  },
  {
    key: 4,
    name: "Vol.055 你的嘴唇为什么起泡.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "24.24 MB",
  },
  {
    key: 5,
    name: "Vol.056 蜂王浆与性激素.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.54 MB",
  },
  {
    key: 6,
    name: "Vol.057 那些年我们吃过的人.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.49 MB",
  },
  {
    key: 7,
    name: "Vol.058 一个细胞能有多大.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "55.42 MB",
  },
  {
    key: 8,
    name: "Vol.059 为什么女人能分辨更多色号.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "34.38 MB",
  },
  {
    key: 9,
    name: "Vol.060 谁能长生不老.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "78.26 MB",
  },
  {
    key: 10,
    name: "Vol.061 昆虫的蛹里发生了什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.81 MB",
  },
  {
    key: 11,
    name: "Vol.062 为什么1+1=2.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "15.28 MB",
  },
  {
    key: 12,
    name: "Vol.063 你为什么口腔溃疡.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "25.5 MB",
  },
  {
    key: 13,
    name: "Vol.064 流火时节的天蝎座.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "63.42 MB",
  },
  {
    key: 14,
    name: "Vol.065 巫婆为什么戴尖帽子.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.05 MB",
  },
  {
    key: 15,
    name: "Vol.066 你为什么要换牙.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "28.93 MB",
  },
  {
    key: 16,
    name: "Vol.067 怎样画纹章.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "62.73 MB",
  },
  {
    key: 17,
    name: "Vol.068 星云，群星的归宿.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "67.75 MB",
  },
  {
    key: 18,
    name: "Vol.069 怎样画树叶.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.89 MB",
  },
  {
    key: 19,
    name: "Vol.070 虫的附肢（上）.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.59 MB",
  },
  {
    key: 20,
    name: "Vol.071 蟲的附肢（下）.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "68.27 MB",
  },
  {
    key: 21,
    name: "Vol.072 咖啡对你做了什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "28.24 MB",
  },
  {
    key: 22,
    name: "Vol.073 算盘的往事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "24.21 MB",
  },
  {
    key: 23,
    name: "Vol.074 图灵斑图：生命图案的奥秘.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.55 MB",
  },
  {
    key: 24,
    name: "Vol.075 猫的瞳孔为什么竖着.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.66 MB",
  },
  {
    key: 25,
    name: "Vol.076 为什么现代艺术家不好好画画.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "77.87 MB",
  },
  {
    key: 26,
    name: "Vol.077 重返自然的新艺术运动.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "89.99 MB",
  },
  {
    key: 27,
    name: "Vol.078 什么是表面张力.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "31.96 MB",
  },
  {
    key: 28,
    name: "Vol.079 比基尼是怎么来的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "57.77 MB",
  },
  {
    key: 29,
    name: "Vol.080 人类文明是怎样诞生的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.69 MB",
  },
  {
    key: 30,
    name: "Vol.081 埃舍尔的自我指涉.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "66.18 MB",
  },
  {
    key: 31,
    name: "Vol.082 西瓜为什么中间最甜.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.39 MB",
  },
  {
    key: 32,
    name: "Vol.083 猫娘养的弓形虫.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.13 MB",
  },
  {
    key: 33,
    name: "Vol.084 崂山道士和量子力学.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.21 MB",
  },
  {
    key: 34,
    name: "Vol.085 儿童性教育一则.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "31.18 MB",
  },
  {
    key: 35,
    name: "Vol.086 密集恐惧症的大休克.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "69.39 MB",
  },
  {
    key: 36,
    name: "Vol.087 什么是平行宇宙？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.34 MB",
  },
  {
    key: 37,
    name: "Vol.088 肚脐通到哪.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "32.68 MB",
  },
  {
    key: 38,
    name: "Vol.089 哥德尔、埃舍尔、巴赫.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "19.57 MB",
  },
  {
    key: 39,
    name: "Vol.090 哥德尔证明.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "24.08 MB",
  },
  {
    key: 40,
    name: "Vol.091 夜空为什么是黑色的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.08 MB",
  },
  {
    key: 41,
    name: "Vol.092 如何破译失传的文字.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.44 MB",
  },
  {
    key: 42,
    name: "Vol.093 为什么你的牙齿不好看.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.26 MB",
  },
  {
    key: 43,
    name: "Vol.094 如何打造《纪念碑谷》的建筑奇观.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.58 MB",
  },
  {
    key: 44,
    name: "Vol.095 螺壳里的万籁.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "28.61 MB",
  },
  {
    key: 45,
    name: "Vol.096 中国人的祖先从哪来.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.67 MB",
  },
  {
    key: 46,
    name: "Vol.097 中国瓷器基础指南：单色釉.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.29 MB",
  },
  {
    key: 47,
    name: "Vol.098 中国陶瓷基础指南：彩瓷.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "52.47 MB",
  },
  {
    key: 48,
    name: "Vol.099 进化有方向吗.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.68 MB",
  },
  {
    key: 49,
    name: "Vol.100 混乱博物馆一百期啦！.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "6.92 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
