<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/混乱博物馆/Vol.101-150/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.101 一个蓝色的故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "64.37 MB",
  },
  {
    key: 1,
    name: "Vol.102 压缩机与鹦鹉螺：螺线的故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.49 MB",
  },
  {
    key: 2,
    name: "Vol.103 为什么勇者总要斗恶龙.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "79.02 MB",
  },
  {
    key: 3,
    name: "Vol.104 钢的琴.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.89 MB",
  },
  {
    key: 4,
    name: "Vol.105 一个黃色的故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "49.17 MB",
  },
  {
    key: 5,
    name: "Vol.106 男人的乳头与男人的未来.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "29.37 MB",
  },
  {
    key: 6,
    name: "Vol.107 星座之王.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "50.63 MB",
  },
  {
    key: 7,
    name: "Vol.108 生活在更多的维度里.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "85.42 MB",
  },
  {
    key: 8,
    name: "Vol.109 你为什么这么重.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.83 MB",
  },
  {
    key: 9,
    name: "Vol.110 基因的时代.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "40.26 MB",
  },
  {
    key: 10,
    name: "Vol.111 动画是什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "81.74 MB",
  },
  {
    key: 11,
    name: "Vol.112 海星的变态生涯.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.98 MB",
  },
  {
    key: 12,
    name: "Vol.113 一个红色的故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "66.55 MB",
  },
  {
    key: 13,
    name: "Vol.114 又一个红色的故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.61 MB",
  },
  {
    key: 14,
    name: "Vol.115 为什么我们看不见空气.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.7 MB",
  },
  {
    key: 15,
    name: "Vol.116 为什么圣诞树顶有五角星.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "80.1 MB",
  },
  {
    key: 16,
    name: "Vol.117 呼吸时，人体内发生了什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "67.63 MB",
  },
  {
    key: 17,
    name: "Vol.118 构成世界的微粒.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "58.72 MB",
  },
  {
    key: 18,
    name: "Vol.119 建国后成精.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "73.88 MB",
  },
  {
    key: 19,
    name: "Vol.120 山姆大叔上位史.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "67.5 MB",
  },
  {
    key: 20,
    name: "Vol.121 怎样才能饭来张口.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "81.33 MB",
  },
  {
    key: 21,
    name: "Vol.122 画家为什么画得像照片.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "77.29 MB",
  },
  {
    key: 22,
    name: "Vol.123 什么动物最能生.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "85.06 MB",
  },
  {
    key: 23,
    name: "Vol.124 男孩子才戴贞操带.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.27 MB",
  },
  {
    key: 24,
    name: "Vol.125 无穷大等于几——从音乐到量子论.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "17.6 MB",
  },
  {
    key: 25,
    name: "Vol.126 多巴胺——让你舒服的秘密.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.3 MB",
  },
  {
    key: 26,
    name: "Vol.127 中式英语是什么味儿.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "26.31 MB",
  },
  {
    key: 27,
    name: "Vol.128 光为什么这样传播.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "17.75 MB",
  },
  {
    key: 28,
    name: "Vol.129 臭味消除指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.09 MB",
  },
  {
    key: 29,
    name: "Vol.130 马戏团里的畸形秀.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.7 MB",
  },
  {
    key: 30,
    name: "Vol.131 地心说错在哪？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "57.81 MB",
  },
  {
    key: 31,
    name: "Vol.132 那些吃活人的动物.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "57.09 MB",
  },
  {
    key: 32,
    name: "Vol.133 剧毒物质排行榜.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "62.1 MB",
  },
  {
    key: 33,
    name: "Vol.134 人造人的炼制成果.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "59.87 MB",
  },
  {
    key: 34,
    name: "Vol.135 环球梅毒史.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "77.0 MB",
  },
  {
    key: 35,
    name: "Vol.136 春节淀粉宴.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.15 MB",
  },
  {
    key: 36,
    name: "Vol.137 反科学的科幻故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.63 MB",
  },
  {
    key: 37,
    name: "Vol.138 为什么大草莓多畸形？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "64.12 MB",
  },
  {
    key: 38,
    name: "Vol.139 为什么交通这么堵.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.76 MB",
  },
  {
    key: 39,
    name: "Vol.140 那些有毒的蔬菜.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "57.68 MB",
  },
  {
    key: 40,
    name: "Vol.141 牛顿的炼金生涯.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "85.54 MB",
  },
  {
    key: 41,
    name: "Vol.142 人们对狗做了什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.38 MB",
  },
  {
    key: 42,
    name: "Vol.143 空想性错视：从平家蟹到脸盲症.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.05 MB",
  },
  {
    key: 43,
    name: "Vol.144 空想性错视：从火星人脸到颜文字.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "38.57 MB",
  },
  {
    key: 44,
    name: "Vol.145 超光速简易方法一则.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.2 MB",
  },
  {
    key: 45,
    name: "Vol.146 植物为什么进化成绿色？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "62.94 MB",
  },
  {
    key: 46,
    name: "Vol.147 霍金辐射.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.87 MB",
  },
  {
    key: 47,
    name: "Vol.148 野生肉棒鉴定录.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "66.56 MB",
  },
  {
    key: 48,
    name: "Vol.149 拟态专家大赏.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "67.96 MB",
  },
  {
    key: 49,
    name: "Vol.150 拟态是怎么进化出来的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "57.23 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
