<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/混乱博物馆/Vol.251-300/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.251 人体的艺术.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "72.17 MB",
  },
  {
    key: 1,
    name: "Vol.252 奶之源.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "69.51 MB",
  },
  {
    key: 2,
    name: "Vol.253 为什么你沒见过闰正月.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "50.07 MB",
  },
  {
    key: 3,
    name: "Vol.254 猫和老鼠的欢乐节奏.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "67.69 MB",
  },
  {
    key: 4,
    name: "Vol.255 神圣的遗骸.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "92.74 MB",
  },
  {
    key: 5,
    name: "Vol.256 动物有语言吗.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "67.77 MB",
  },
  {
    key: 6,
    name: "Vol.257 5G背后的两个男人.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "74.91 MB",
  },
  {
    key: 7,
    name: "Vol.258 普罗米修斯的礼物.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "76.88 MB",
  },
  {
    key: 8,
    name: "Vol.259 罗马人造的又大又园.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "102.14 MB",
  },
  {
    key: 9,
    name: "Vol.260 如何星际旅行不迷航.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "130.87 MB",
  },
  {
    key: 10,
    name: "Vol.261 你的眼睛为何如此贫穷.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "48.89 MB",
  },
  {
    key: 11,
    name: "Vol.262 放大世界的极限之旅.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.45 MB",
  },
  {
    key: 12,
    name: "Vol.263 动物为什么也会社交恐惧.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "106.62 MB",
  },
  {
    key: 13,
    name: "Vol.264 什么样的冰块可以烫死人？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "105.35 MB",
  },
  {
    key: 14,
    name: "Vol.265 最可怕的传染病是什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "116.02 MB",
  },
  {
    key: 15,
    name: "Vol.266 宜家、苹果的性冷淡风是怎么来的？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "62.37 MB",
  },
  {
    key: 16,
    name: "Vol.267 地铁有什么了不起.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "91.63 MB",
  },
  {
    key: 17,
    name: "Vol.268 圣诞到底是谁的生日.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "140.83 MB",
  },
  {
    key: 18,
    name: "Vol.269 为什么我的世界是立体的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "100.3 MB",
  },
  {
    key: 19,
    name: "Vol.270 怎么冻猪肉更好吃.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "85.1 MB",
  },
  {
    key: 20,
    name: "Vol.271 米老鼠是什么鼠.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "94.24 MB",
  },
  {
    key: 21,
    name: "Vol.272 病毒是如何欺骗你的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "140.58 MB",
  },
  {
    key: 22,
    name: "Vol.273 交配的最佳时机.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "84.1 MB",
  },
  {
    key: 23,
    name: "Vol.274 什么时候你会瞳孔放大.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "98.87 MB",
  },
  {
    key: 24,
    name: "Vol.275 什么样的波最有內容.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "128.32 MB",
  },
  {
    key: 25,
    name: "Vol.276 癌细胞究竟狡猾在哪.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "113.57 MB",
  },
  {
    key: 26,
    name: "Vol.277 如何驯化免疫细胞.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "104.38 MB",
  },
  {
    key: 27,
    name: "Vol.278 如何更聪明地进行计算.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "115.68 MB",
  },
  {
    key: 28,
    name: "Vol.279 如何方便上太空.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.95 MB",
  },
  {
    key: 29,
    name: "Vol.280 汽车人离我们还有多远.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "73.03 MB",
  },
  {
    key: 30,
    name: "Vol.281 蜜蜂有什么了不起.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "117.67 MB",
  },
  {
    key: 31,
    name: "Vol.282 如何让免疫细胞再次伟大.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "93.54 MB",
  },
  {
    key: 32,
    name: "Vol.283 人类·究竟对·免疫做了什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "109.26 MB",
  },
  {
    key: 33,
    name: "Vol.284 新颜色故事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.39 MB",
  },
  {
    key: 34,
    name: "Vol.285 “蝌蚪”如何像军队一样战斗.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "61.9 MB",
  },
  {
    key: 35,
    name: "Vol.286 你的耳朵对声音做了什么.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "57.43 MB",
  },
  {
    key: 36,
    name: "Vol.287 棍棒之下出芯片.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "75.06 MB",
  },
  {
    key: 37,
    name: "Vol.288 黑人音乐有什么了不起.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "155.9 MB",
  },
  {
    key: 38,
    name: "Vol.289 恐龙肉好吃吗.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "101.47 MB",
  },
  {
    key: 39,
    name: "Vol.290 你是怎么变黑的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "100.0 MB",
  },
  {
    key: 40,
    name: "Vol.291 怎么才能证明一款药有效.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "137.45 MB",
  },
  {
    key: 41,
    name: "Vol.292 你为什么还在长智齿.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "92.36 MB",
  },
  {
    key: 42,
    name: "Vol.293 爱神丘比特之迷.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "101.94 MB",
  },
  {
    key: 43,
    name: "Vol.294 怎样成为一条合格的电鳗.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "106.94 MB",
  },
  {
    key: 44,
    name: "Vol.295 齿轮如何转动世界.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "88.09 MB",
  },
  {
    key: 45,
    name: "Vol.296 月亮究竟由谁掌管.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "71.94 MB",
  },
  {
    key: 46,
    name: "Vol.297 猫杂种们是如何诞生的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "125.46 MB",
  },
  {
    key: 47,
    name: "Vol.298 不可描述的人体改造术.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "107.8 MB",
  },
  {
    key: 48,
    name: "Vol.299 人类可以战胜传染病吗.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "94.25 MB",
  },
  {
    key: 49,
    name: "Vol.300 寻找黃金国.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "165.8 MB",
  },
  {
    key: 50,
    name: "Vol.300.5 寻找黄金国·解.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "16.66 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
