<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/混乱博物馆/Vol.201-250/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.201 毒瘾的真相.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "23.18 MB",
  },
  {
    key: 1,
    name: "Vol.202 太阳神的遗产.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "49.49 MB",
  },
  {
    key: 2,
    name: "Vol.203 你是怎么过敏的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.38 MB",
  },
  {
    key: 3,
    name: "Vol.204 西洋的东方.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.39 MB",
  },
  {
    key: 4,
    name: "Vol.205 调皮的蘑菇头.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "22.88 MB",
  },
  {
    key: 5,
    name: "Vol.206 成为机器人.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "19.27 MB",
  },
  {
    key: 6,
    name: "Vol.207 从几何二字说起.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "70.65 MB",
  },
  {
    key: 7,
    name: "Vol.208 圆周率的征途.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.35 MB",
  },
  {
    key: 8,
    name: "Vol.209 卧看牵牛牛织女星.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "68.91 MB",
  },
  {
    key: 9,
    name: "Vol.210 嗜血者.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.4 MB",
  },
  {
    key: 10,
    name: "Vol.211 給大自然写真.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.38 MB",
  },
  {
    key: 11,
    name: "Vol.212 动物为什么没有蓝色素.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "73.64 MB",
  },
  {
    key: 12,
    name: "Vol.213 琥珀之路.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "74.3 MB",
  },
  {
    key: 13,
    name: "Vol.214人类有没有亚种.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "46.44 MB",
  },
  {
    key: 14,
    name: "Vol.215 从迷宫到扫地机器人.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "72.67 MB",
  },
  {
    key: 15,
    name: "Vol.216 满世界的螨.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "58.75 MB",
  },
  {
    key: 16,
    name: "Vol.217 人类未来会进化成什么样子？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.67 MB",
  },
  {
    key: 17,
    name: "Vol.218 进化的阶次.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "23.49 MB",
  },
  {
    key: 18,
    name: "Vol.219 美人头.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "69.82 MB",
  },
  {
    key: 19,
    name: "Vol.220 进化上的不约而同.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "40.76 MB",
  },
  {
    key: 20,
    name: "Vol.221 弄不清的草药.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "98.24 MB",
  },
  {
    key: 21,
    name: "Vol.222 彩虹为什么是弯的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "26.92 MB",
  },
  {
    key: 22,
    name: "Vol.223 全体自然数的“和”是-1_12（重制版）.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "22.47 MB",
  },
  {
    key: 23,
    name: "Vol.224 从哥特式到学院派的4分钟.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "93.7 MB",
  },
  {
    key: 24,
    name: "Vol.225 益智玩具有几种.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "68.22 MB",
  },
  {
    key: 25,
    name: "Vol.226 热的里程碑.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "91.38 MB",
  },
  {
    key: 26,
    name: "Vol.227 甜蜜的往事.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "80.25 MB",
  },
  {
    key: 27,
    name: "Vol.228 视错觉大赏.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.38 MB",
  },
  {
    key: 28,
    name: "Vol.229 虛假的甜蜜.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "50.32 MB",
  },
  {
    key: 29,
    name: "Vol.230 旋涡.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "92.46 MB",
  },
  {
    key: 30,
    name: "Vol.231 人的头发为什么有旋？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "14.21 MB",
  },
  {
    key: 31,
    name: "Vol.232 星辰之死.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.14 MB",
  },
  {
    key: 32,
    name: "Vol.233 深海的鱼.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.19 MB",
  },
  {
    key: 33,
    name: "Vol.234 无穷小量的回忆录.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "29.48 MB",
  },
  {
    key: 34,
    name: "Vol.235 漫话漫画.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.3 MB",
  },
  {
    key: 35,
    name: "Vol.236 辣之源.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "69.4 MB",
  },
  {
    key: 36,
    name: "Vol.237 描绘世界.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "72.85 MB",
  },
  {
    key: 37,
    name: "Vol.238 色彩的空间.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "52.89 MB",
  },
  {
    key: 38,
    name: "Vol.239 一个故事的结束.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "83.74 MB",
  },
  {
    key: 39,
    name: "Vol.240 为什么我们仰望星空会震撼.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "46.26 MB",
  },
  {
    key: 40,
    name: "Vol.241 骆驼来自哪里.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "34.11 MB",
  },
  {
    key: 41,
    name: "Vol.242 一个肥美的故事·上.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "37.05 MB",
  },
  {
    key: 42,
    name: "Vol.243 鲸鱼为什么是偶蹄目？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.6 MB",
  },
  {
    key: 43,
    name: "Vol.244 好吃的猪肉从哪里来？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "68.62 MB",
  },
  {
    key: 44,
    name: "Vol.245 人类的体温为何是37度.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "20.47 MB",
  },
  {
    key: 45,
    name: "Vol.246 来个贾维斯般的管家.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "58.91 MB",
  },
  {
    key: 46,
    name: "Vol.247 食草动物才不是吃素的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.96 MB",
  },
  {
    key: 47,
    name: "Vol.248 东北大米为什么如此好吃.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.94 MB",
  },
  {
    key: 48,
    name: "Vol.249 数人头的科学方法.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.45 MB",
  },
  {
    key: 49,
    name: "Vol.250 欧洲国旗为什么大多是三色旗.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "72.92 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
