<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileAudioRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/原创专辑/MULTIPLY_正片叠底/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "444（足球） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "27.53 MB",
  },
  {
    key: 1,
    name: "60s B&Y（电影） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "53.8 MB",
  },
  {
    key: 2,
    name: "ACHOO!（不粘锅） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "37.28 MB",
  },
  {
    key: 3,
    name: "AIM（北斗） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "33.92 MB",
  },
  {
    key: 4,
    name: "AWAKEN（区块链） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "25.89 MB",
  },
  {
    key: 5,
    name: "Bazooka（顶级篮球鞋） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "44.19 MB",
  },
  {
    key: 6,
    name: "Beeeep!（养蜂） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "48.85 MB",
  },
  {
    key: 7,
    name: "Big Spender（爆款公墓） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "35.59 MB",
  },
  {
    key: 8,
    name: "Blip（圆珠笔） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "32.05 MB",
  },
  {
    key: 9,
    name: "BOSSY（人工岛） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "40.45 MB",
  },
  {
    key: 10,
    name: "BOUNCE 2（马达） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "32.7 MB",
  },
  {
    key: 11,
    name: "Bricks（期货） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "32.26 MB",
  },
  {
    key: 12,
    name: "Careful（过山车） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "33.9 MB",
  },
  {
    key: 13,
    name: "CAVALER（假币） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "28.05 MB",
  },
  {
    key: 14,
    name: "CHEFE（身份证） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "27.15 MB",
  },
  {
    key: 15,
    name: "Code（手机拍照） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "42.88 MB",
  },
  {
    key: 16,
    name: "Cold（刷卡消费） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "28.83 MB",
  },
  {
    key: 17,
    name: "COONER（硬盘） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "20.6 MB",
  },
  {
    key: 18,
    name: "DEMONS（地图） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "31.33 MB",
  },
  {
    key: 19,
    name: "Distant（网盘） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "50.98 MB",
  },
  {
    key: 20,
    name: "Dugg（电梯） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "32.79 MB",
  },
  {
    key: 21,
    name: "Fury（炒股Part2） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "26.71 MB",
  },
  {
    key: 22,
    name: "Glasses（X光） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "37.66 MB",
  },
  {
    key: 23,
    name: "GOOD SHOW (装修) - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "54.43 MB",
  },
  {
    key: 24,
    name: "Half Winter(养鳖) - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "40.94 MB",
  },
  {
    key: 25,
    name: "Hazard（芯片） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "58.72 MB",
  },
  {
    key: 26,
    name: "Heat Up（二手书Part2） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "24.61 MB",
  },
  {
    key: 27,
    name: "Heeyha（游戏手机） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "21.54 MB",
  },
  {
    key: 28,
    name: "Hope（人造肉Part2） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "29.11 MB",
  },
  {
    key: 29,
    name: "HORROR 1981（电动车自燃） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "32.36 MB",
  },
  {
    key: 30,
    name: "I Ja Wansum Papers（顶级润滑油） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "25.01 MB",
  },
  {
    key: 31,
    name: "I Should Have（非牛顿流体） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "25.14 MB",
  },
  {
    key: 32,
    name: "Illusions（电动汽车） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "55.65 MB",
  },
  {
    key: 33,
    name: "Jaws（远程办公） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "38.33 MB",
  },
  {
    key: 34,
    name: "Jumper（BT种子） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "29.07 MB",
  },
  {
    key: 35,
    name: "Jumping（温馨预告片） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "17.58 MB",
  },
  {
    key: 36,
    name: "K9（机票） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "32.04 MB",
  },
  {
    key: 37,
    name: "KINGSTON（固态硬盘） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "35.18 MB",
  },
  {
    key: 38,
    name: "Last Time（口水） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "40.14 MB",
  },
  {
    key: 39,
    name: "Let It Burn（火化） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "23.38 MB",
  },
  {
    key: 40,
    name: "LONG WAY（风力发电机） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "30.74 MB",
  },
  {
    key: 41,
    name: "Lust（5000公里地铁） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "32.74 MB",
  },
  {
    key: 42,
    name: "M.C.T （配眼镜） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "30.11 MB",
  },
  {
    key: 43,
    name: "Mass Appeal（人工降雨） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "27.52 MB",
  },
  {
    key: 44,
    name: "MAZE（马桶） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "27.5 MB",
  },
  {
    key: 45,
    name: "Mobb（碰碰车） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "32.42 MB",
  },
  {
    key: 46,
    name: "My Type（毛衣） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "31.88 MB",
  },
  {
    key: 47,
    name: "No Longer（一秒有多长） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "24.4 MB",
  },
  {
    key: 48,
    name: "Not Cool But Cole（淘金Part2） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "37.07 MB",
  },
  {
    key: 49,
    name: "October（核酸检测） - 回形针PaperClip.flac",
    type: <FileAudioRegular />,
    type_name: "audio",
    time: "2021.9.29",
    size: "34.29 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
