<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/回形针PaperClip/Vol/51-100/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.051 如何花 10 亿美元研发一款有效的抗癌药.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.94 MB",
  },
  {
    key: 1,
    name: "Vol.052 你的手机是怎么上网的？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "55.62 MB",
  },
  {
    key: 2,
    name: "Vol.053 助听器如何拯救耳聋？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.04 MB",
  },
  {
    key: 3,
    name: "Vol.054 ATM如何保护人民币的安全 ？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.61 MB",
  },
  {
    key: 4,
    name: "Vol.055 怎样才能种出刚正不阿的行道树？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.75 MB",
  },
  {
    key: 5,
    name: "Vol.056 如何科学地吃辣椒？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "34.19 MB",
  },
  {
    key: 6,
    name: "Vol.057 原子弹制造指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "50.8 MB",
  },
  {
    key: 7,
    name: "Vol.058 香烟如何让你上瘾？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.98 MB",
  },
  {
    key: 8,
    name: "Vol.059 如何在中国修建 5000 公里地铁 ？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.39 MB",
  },
  {
    key: 9,
    name: "Vol.060 如何打造一双顶级篮球鞋？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "38.46 MB",
  },
  {
    key: 10,
    name: "Vol.061 如何科学的离婚.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.13 MB",
  },
  {
    key: 11,
    name: "Vol.062 你买机票的时候究竟发生了什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "38.51 MB",
  },
  {
    key: 12,
    name: "Vol.063 如何打造一座爆款公墓？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.54 MB",
  },
  {
    key: 13,
    name: "Vol.064 你的手机是如何拍照的？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "34.5 MB",
  },
  {
    key: 14,
    name: "Vol.065 如何防止你的电动车自燃？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "48.51 MB",
  },
  {
    key: 15,
    name: "Vol.066 X光如何看穿你的颈椎、腰椎病？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "29.27 MB",
  },
  {
    key: 16,
    name: "Vol.067 你家装修的时候究竟发生了什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "91.12 MB",
  },
  {
    key: 17,
    name: "Vol.068 如何打造一款顶级润滑油？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.1 MB",
  },
  {
    key: 18,
    name: "Vol.069 如何科学地配一副眼镜？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.8 MB",
  },
  {
    key: 19,
    name: "Vol.070 一秒到底有多长？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "52.92 MB",
  },
  {
    key: 20,
    name: "Vol.071 如何科学地分析你的口水？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.36 MB",
  },
  {
    key: 21,
    name: "Vol.072 你的硬盘是如何储存数据的？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.66 MB",
  },
  {
    key: 22,
    name: "Vol.073 怎样活着从电梯走出来？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "49.27 MB",
  },
  {
    key: 23,
    name: "Vol.074 如何靠养鳖发家致富？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "82.61 MB",
  },
  {
    key: 24,
    name: "Vol.075 别再问我什么叫 BT 种子.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "64.59 MB",
  },
  {
    key: 25,
    name: "Vol.076 如何科学地火化遗体？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "97.92 MB",
  },
  {
    key: 26,
    name: "Vol.077 中国的网盘为什么这么难用？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.58 MB",
  },
  {
    key: 27,
    name: "Vol.078 淘金致富指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "137.9 MB",
  },
  {
    key: 28,
    name: "Vol.079 如何成为钓鱼高手.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "79.08 MB",
  },
  {
    key: 29,
    name: "Vol.080 如何打造一把爆款键盘？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "52.89 MB",
  },
  {
    key: 30,
    name: "Vol.081 5G 是如何诞生的？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.42 MB",
  },
  {
    key: 31,
    name: "Vol.082  如何成为一名动感 DJ？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "113.3 MB",
  },
  {
    key: 32,
    name: "Vol.083 如何科学地消灭蟑螂？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "78.7 MB",
  },
  {
    key: 33,
    name: "Vol.084 期货和你的生活有什么关系？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "70.19 MB",
  },
  {
    key: 34,
    name: "Vol.085 你丢的垃圾都去哪儿了？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "129.97 MB",
  },
  {
    key: 35,
    name: "Vol.086 如何建造一座人工岛.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "71.94 MB",
  },
  {
    key: 36,
    name: "Vol.087 你吃的盐都从哪来？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "57.49 MB",
  },
  {
    key: 37,
    name: "Vol.088 为什么中国的足球赛这么难看？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "63.9 MB",
  },
  {
    key: 38,
    name: "Vol.089 如何打造一款强劲的马达？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "55.74 MB",
  },
  {
    key: 39,
    name: "Vol.090 如何科学地制造降雨？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "63.61 MB",
  },
  {
    key: 40,
    name: "Vol.091 如何做出鲜活的动物标本？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "48.97 MB",
  },
  {
    key: 41,
    name: "Vol.092 如何打造顺滑好写的圆珠笔？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "38.44 MB",
  },
  {
    key: 42,
    name: "Vol.093 为什么你炒股总是亏钱？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "41.6 MB",
  },
  {
    key: 43,
    name: "Vol.094 假肢如何拯救身体残疾？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "49.39 MB",
  },
  {
    key: 44,
    name: "Vol.095 如何造一卷温柔体贴的卫生纸？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.24 MB",
  },
  {
    key: 45,
    name: "Vol.096 如何科学地矫正牙齿？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.54 MB",
  },
  {
    key: 46,
    name: "Vol.097 为什么在中国买彩票一定亏？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.26 MB",
  },
  {
    key: 47,
    name: "Vol.098 不粘锅如何拯救你的厨房？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.4 MB",
  },
  {
    key: 48,
    name: "Vol.099 造假币为什么这么难？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "79.72 MB",
  },
  {
    key: 49,
    name: "Vol.100 来自回形针的挑战信.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "13.36 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
