<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/回形针PaperClip/Vol/101-150/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.101 如何做出令人欲罢不能的炸鸡？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "74.43 MB",
  },
  {
    key: 1,
    name: "Vol.102 怎样画一张地图？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "58.76 MB",
  },
  {
    key: 2,
    name: "Vol.103 防弹衣如何救你的命？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.85 MB",
  },
  {
    key: 3,
    name: "Vol.104 你好！查水表！.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "39.43 MB",
  },
  {
    key: 4,
    name: "Vol.105 如何科学地管理图书馆？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.54 MB",
  },
  {
    key: 5,
    name: "Vol.106 过山车如何让你尖叫？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "76.51 MB",
  },
  {
    key: 6,
    name: "Vol.107 如何成为一个有身份的人？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.28 MB",
  },
  {
    key: 7,
    name: "Vol.108 怎样科学地放电影？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "52.92 MB",
  },
  {
    key: 8,
    name: "Vol.109 马桶如何吸走你的大便？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.83 MB",
  },
  {
    key: 9,
    name: "Vol.110 如何建一座人畜无害的动物园？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "62.98 MB",
  },
  {
    key: 10,
    name: "Vol.111 如何做一块逼真的人造肉？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "52.76 MB",
  },
  {
    key: 11,
    name: "Vol.112 区块链到底是什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.65 MB",
  },
  {
    key: 12,
    name: "Vol.113 如何科学地刷信用卡？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "39.72 MB",
  },
  {
    key: 13,
    name: "Vol.114 如何为14亿人调度飞机？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "99.57 MB",
  },
  {
    key: 14,
    name: "Vol.115 为什么你要献血？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.44 MB",
  },
  {
    key: 15,
    name: "Vol.116 如何把一只羊变成毛衣？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.83 MB",
  },
  {
    key: 16,
    name: "Vol.117 为什么你还买不到口罩？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.41 MB",
  },
  {
    key: 17,
    name: "Vol.118 你的 App 对你的隐私做了什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.39 MB",
  },
  {
    key: 18,
    name: "Vol.119 如何准确地预报天气？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "57.99 MB",
  },
  {
    key: 19,
    name: "Vol.120 二维码的秘密.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "261.12 MB",
  },
  {
    key: 20,
    name: "Vol.121 开锁师傅对你的锁做了什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "71.5 MB",
  },
  {
    key: 21,
    name: "Vol.122 ICU 病房里究竟发生了什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "49.41 MB",
  },
  {
    key: 22,
    name: "Vol.123 如何吃上肥美的大鱿鱼.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.87 MB",
  },
  {
    key: 23,
    name: "Vol.124 海底光缆如何连接全球互联网.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "110.0 MB",
  },
  {
    key: 24,
    name: "Vol.125 生物类似药如何抗击乳腺癌.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "64.62 MB",
  },
  {
    key: 25,
    name: "Vol.126 如何让帆船逆风航行？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "142.0 MB",
  },
  {
    key: 26,
    name: "Vol.127 为什么女生的内衣总是不合身？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "37.26 MB",
  },
  {
    key: 27,
    name: "Vol.128 光盘里究竟有什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.27 MB",
  },
  {
    key: 28,
    name: "Vol.129 为什么你的脚这么臭.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "82.56 MB",
  },
  {
    key: 29,
    name: "Vol.130 北斗卫星为你做了什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "88.44 MB",
  },
  {
    key: 30,
    name: "Vol.131 为什么拍电影要用斯坦尼康？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "172.22 MB",
  },
  {
    key: 31,
    name: "Vol.132 如何科学测量你的体温？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "84.04 MB",
  },
  {
    key: 32,
    name: "Vol.133 如何科学地消灭蚊子？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "138.26 MB",
  },
  {
    key: 33,
    name: "Vol.134 核酸检测如何高效筛查新冠肺炎？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "49.75 MB",
  },
  {
    key: 34,
    name: "Vol.135 养蜂致富指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "110.0 MB",
  },
  {
    key: 35,
    name: "Vol.136 如何成为一名金牌电焊工？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "70.13 MB",
  },
  {
    key: 36,
    name: "Vol.137 如何在纳米尺度雕刻芯片？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "160.43 MB",
  },
  {
    key: 37,
    name: "Vol.138 如何用 DNA 追捕真凶？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "135.56 MB",
  },
  {
    key: 38,
    name: "Vol.139 如何精确控制母鸡批量下蛋？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "61.37 MB",
  },
  {
    key: 39,
    name: "Vol.140 如何科学地拆除炸弹？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.66 MB",
  },
  {
    key: 40,
    name: "Vol.141 氢弹制造指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "97.91 MB",
  },
  {
    key: 41,
    name: "Vol.142 水痘-带状疱疹病毒如何伴你一生.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.51 MB",
  },
  {
    key: 42,
    name: "Vol.143 嫦娥五号：重返地球.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "65.72 MB",
  },
  {
    key: 43,
    name: "Vol.144 AED 如何拯救濒死的人.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "69.32 MB",
  },
  {
    key: 44,
    name: "Vol.145 HIV 自救指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "104.23 MB",
  },
  {
    key: 45,
    name: "Vol.146 速溶咖啡为什么这么难喝.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "105.39 MB",
  },
  {
    key: 46,
    name: "Vol.147 长租公寓是如何爆雷的.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "136.15 MB",
  },
  {
    key: 47,
    name: "Vol.148 如何让你的胃免受伤害.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "71.36 MB",
  },
  {
    key: 48,
    name: "Vol.149 螺蛳粉如何制霸中国.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "95.88 MB",
  },
  {
    key: 49,
    name: "Vol.150 狙击手如何一枪毙命？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "46.82 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
