<template><n-data-table :columns="columns" :data="data" /></template>
<script>
import { h, defineComponent } from "vue";
import { NDataTable, NButton } from "naive-ui";
import { FileVideoRegular } from "@vicons/fa";
import AVideo from "/src/components/AVideo.vue";
import AImage from "/src/components/AImage.vue";
import AAudio from "/src/components/AAudio.vue";
const urlTop = "https://file.hsyhx.top/回形针PaperClip/Vol/1-50/";
const createColumns = () => {
  return [
    {
      type: "expand",
      renderExpand: (rowData) => {
        if (rowData.type_name == "video") {
          return h(AVideo, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "image") {
          return h(AImage, { src: urlTop + rowData.name });
        } else if (rowData.type_name == "audio") {
          return h(AAudio, { src: urlTop + rowData.name });
        }
      },
    },
    {
      title: "文件名",
      key: "name",
      render(row) {
        return h(
          NButton,
          { text: "" },
          { icon: () => row.type, default: () => row.name }
        );
      },
    },
    { title: "最后更新时间", key: "time" },
    { title: "大小", key: "size" },
  ];
};
const createData = () => [
  {
    key: 0,
    name: "Vol.001 摄像头如何监控十三亿人.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "53.25 MB",
  },
  {
    key: 1,
    name: "Vol.002 如何制造爆款冥币.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "48.74 MB",
  },
  {
    key: 2,
    name: "Vol.003 垃圾短信群发指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "32.72 MB",
  },
  {
    key: 3,
    name: "Vol.004 为什么中国人总是在安检.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "56.28 MB",
  },
  {
    key: 4,
    name: "Vol.005 如何实现逼真的砍头.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.16 MB",
  },
  {
    key: 5,
    name: "Vol.006 烂牙修复指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "77.19 MB",
  },
  {
    key: 6,
    name: "Vol.007 如何科学地执行死刑.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "64.95 MB",
  },
  {
    key: 7,
    name: "Vol.008 如何给猪盖章.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "59.83 MB",
  },
  {
    key: 8,
    name: "Vol.009 跑车凭什么这么贵.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.26 MB",
  },
  {
    key: 9,
    name: "Vol.010 混音师如何拯救歌手.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "65.52 MB",
  },
  {
    key: 10,
    name: "Vol.011 如何制造爆款烟花.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "77.08 MB",
  },
  {
    key: 11,
    name: "Vol.012 坦克驾驶指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "30.31 MB",
  },
  {
    key: 12,
    name: "Vol.013 如何拯救秃顶.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.98 MB",
  },
  {
    key: 13,
    name: "Vol.014 如何科学地消灭敏感词.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "22.77 MB",
  },
  {
    key: 14,
    name: "Vol.015 如何经营一家鬼屋.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "76.06 MB",
  },
  {
    key: 15,
    name: "Vol.016 自来水都从哪来.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "29.85 MB",
  },
  {
    key: 16,
    name: "Vol.017 高考作弊攻防战.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "33.87 MB",
  },
  {
    key: 17,
    name: "Vol.018 高速公路收费指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "64.23 MB",
  },
  {
    key: 18,
    name: "Vol.019 如何实现一次华丽的漂移.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "58.49 MB",
  },
  {
    key: 19,
    name: "Vol.020 围棋 AI 养成指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.59 MB",
  },
  {
    key: 20,
    name: "Vol.021 如何科学地给机票定价.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "35.03 MB",
  },
  {
    key: 21,
    name: "Vol.022 如何科学地戒毒.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.49 MB",
  },
  {
    key: 22,
    name: "Vol.023 如何准确定位你的手机.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.8 MB",
  },
  {
    key: 23,
    name: "Vol.024 如何用煤烧出 4 万亿度电.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "61.95 MB",
  },
  {
    key: 24,
    name: "Vol.025 牛如何变成速冻牛排.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.03 MB",
  },
  {
    key: 25,
    name: "Vol.026 摄像头如何抓住你超速、压线、闯红灯.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "51.16 MB",
  },
  {
    key: 26,
    name: "Vol.027 如何制造婴儿奶粉.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "31.33 MB",
  },
  {
    key: 27,
    name: "Vol.028 如何显示准确的颜色.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "38.93 MB",
  },
  {
    key: 28,
    name: "Vol.029 如何打造一款有用的美白护肤品.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "46.17 MB",
  },
  {
    key: 29,
    name: "Vol.030 如何建造一座戒备森严的监狱.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "66.09 MB",
  },
  {
    key: 30,
    name: "Vol.031 怎样打造逼真的引擎声.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "39.38 MB",
  },
  {
    key: 31,
    name: "Vol.032 双眼皮手术指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.16 MB",
  },
  {
    key: 32,
    name: "Vol.033 电动汽车制造指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "47.25 MB",
  },
  {
    key: 33,
    name: "Vol.034 你拉的屎都去哪儿了？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "43.24 MB",
  },
  {
    key: 34,
    name: "Vol.035 如何科学地炸倒一栋楼？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "45.31 MB",
  },
  {
    key: 35,
    name: "Vol.036 如何设计一个逼真的三维模型.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "35.56 MB",
  },
  {
    key: 36,
    name: "Vol.037 快递是如何送到你手中的？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "54.82 MB",
  },
  {
    key: 37,
    name: "Vol.038 香蕉育成指南.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "60.31 MB",
  },
  {
    key: 38,
    name: "Vol.039 如何用机器人打销售电话？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "32.81 MB",
  },
  {
    key: 39,
    name: "Vol.040 如何给无骨鸡爪脱骨？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "37.13 MB",
  },
  {
    key: 40,
    name: "Vol.041 暖气是如何送到你家的？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.32 MB",
  },
  {
    key: 41,
    name: "Vol.042 如何制造爆款宠物.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.52 MB",
  },
  {
    key: 42,
    name: "Vol.043 如何批量制造钻石？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "42.34 MB",
  },
  {
    key: 43,
    name: "Vol.044 锂电池如何拯救当代生活？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "34.53 MB",
  },
  {
    key: 44,
    name: "Vol.045 今天的汽车和百年前有什么区别？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "36.2 MB",
  },
  {
    key: 45,
    name: "Vol.046 手术如何拯救近视眼？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "31.87 MB",
  },
  {
    key: 46,
    name: "Vol.047 低焦油香烟的骗局.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "39.29 MB",
  },
  {
    key: 47,
    name: "Vol.048 你的 App 为什么知道你想买什么？.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "21.95 MB",
  },
  {
    key: 48,
    name: "Vol.049 如何做一根懂事的路灯.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "40.98 MB",
  },
  {
    key: 49,
    name: "Vol.050 如何为十三亿人调度列车.mp4",
    type: <FileVideoRegular />,
    type_name: "video",
    time: "2021.9.29",
    size: "44.6 MB",
  },
];
export default defineComponent({
  components: { NDataTable },
  setup() {
    return { data: createData(), columns: createColumns() };
  },
});
</script>
