name = "ipaperclip-icu-site"
main = "src-worker/index.ts"
compatibility_date = "2023-06-04"
workers_dev = false

[site]
bucket = "./dist/web"

[placement]
mode = "smart"

kv_namespaces = [
  { binding = "__STATIC_CONTENT", id = "8b8430501ee840e8af12e7cd595b96f4" }
]
