name: Telegram
on: [push]
jobs:

  build:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_notification: true
          format: markdown
          message: |
            #Github: [iPaperClipICU/ipaperclip.icu](https://github.com/iPaperClipICU/ipaperclip.icu/) has new commit:
            
            [${{github.sha}}](https://github.com/${{ github.repository }}/commit/${{github.sha}}/): ${{ github.event.commits[0].message }} by ${{ github.actor }}
